#!/bin/bash
#
#SBATCH --partition=gpu                 # partition
#SBATCH --qos=valhala
#SBATCH --nodes=1                       # number of nodes
#SBATCH --ntasks-per-node=1             # number of cores
#SBATCH --mem=24G                       # memory per node
#SBATCH --time=5-00:00                  # time (D-HH:MM)
#SBATCH --output=slurm.%N.%j.out        # STDOUT
#SBATCH --error=slurm.%N.%j.err         # STDERR

# won't work without this
export NCCL_P2P_DISABLE=1
# export NCCL_DEBUG=INFO

source ~/.bashrc
conda activate rnn_env

experiment=logs/vanilla/
optimization_steps=100

for i in $(seq $optimization_steps)
do
    echo "Making gridsearch step."
    srun python gridsearch.py --path $experiment

    echo "Running trainer."
    srun python trainer.py --num_nodes 1 --devices 1 --train_size 1.0 --monitor_checkpoint balanced_acc/val --mode_checkpoint max --monitor_stopping loss/val --mode_stopping min --epochs 250 --path $experiment
done
