{K: 0.1, batch_size: 191, dropout: 0.0, hidden_size: 188, init_points: 40, linear_size: 24,
  loss: mse, lr: 0.0014162106923043887, name: logs/overfitting_K=0.1, num_lin_layers: 2,
  num_rnn_layers: 5, optimizer: adam, precision: 32-true, shuffle_batches: false,
  shuffle_trajectories: true, steps: 45}
