K: 0.1 # list of values for StandardMap

hidden_size: 128
linear_size: 128 # used when num_lin_layers > 1
num_rnn_layers: 2
num_lin_layers: 2
non_linearity: selu
dropout: 0.0 # doesn't seem necessary

batch_size: 256
seq_len: 20 # only have one sequence
loss: mse
optimizer: adam
lr: 0.0001
precision: 32-true

shuffle_trajectories: True # makes sense for linear sampling
shuffle_batches: False # shuffle batches between epochs

gridsearch:
  batch_size: { lower: 64, upper: 512, type: int }
  lr: { lower: -6, upper: -1, type: log }
  num_rnn_layers: { lower: 1, upper: 6, type: int }
  num_lin_layers: { lower: 1, upper: 6, type: int }
  hidden_size: { lower: 32, upper: 256, type: int }
  linear_size: { lower: 32, upper: 256, type: int }
