init_points: 40 # how many points to take from loaded data
steps: 100 # how many steps to take from loaded data
K: 0.1 # list of values for StandardMap

hidden_size: 64
linear_size: 32 # used when num_lin_layers > 1
num_rnn_layers: 2
num_lin_layers: 2
dropout: 0.0

epochs: 4000
batch_size: 256
loss: binary_crossentropy
optimizer: adam
lr: 0.0001
precision: 32-true

shuffle_trajectories: True # makes sense for linear sampling
shuffle_batches: False # shuffle batches between epochs

name: logs/overfitting_K=0.1/0

gridsearch:
  batch_size: { lower: 100, upper: 300, type: int }
  lr: { lower: 0.0001, upper: 0.003, type: float }
  num_rnn_layers: { lower: 1, upper: 5, type: int }
  num_lin_layers: { lower: 1, upper: 5, type: int }
  hidden_size: { lower: 80, upper: 300, type: int }
  linear_size: { lower: 20, upper: 300, type: int }
