steps: 45 # ≤ 100
K: 0.1

hidden_size: 32
linear_size: 32 # used when num_lin_layers > 1
num_rnn_layers: 1
num_lin_layers: 1
dropout: 0.0 # doesn't seem necessary

epochs: 20
batch_size: 256
loss: mse
optimizer: adam
lr: 0.0003
precision: 32-true

shuffle_paths: True # makes sense for linear sampling
shuffle_batches: False # shuffle batches between epochs

name: logs/overfitting_K=0.1/0

gridsearch:
  batch_size: { lower: 150, upper: 230, type: int }
  lr: { lower: 0.0004, upper: 0.002, type: float }
  num_rnn_layers: { lower: 2, upper: 5, type: int }
  num_lin_layers: { lower: 2, upper: 4, type: int }
  hidden_size: { lower: 120, upper: 210, type: int }
  linear_size: { lower: 20, upper: 80, type: int }
