steps: 30
K_upper_lim: 0.3

hidden_size: 64
linear_size: 32 # used when num_lin_layers > 1
num_rnn_layers: 2
num_lin_layers: 2
dropout: 0.0

epochs: 200
batch_size: 256
loss: binary_crossentropy
optimizer: adam
lr: 0.0001
precision: 32-true

shuffle_paths: True # makes sense for linear sampling
shuffle_batches: False # shuffle batches between epochs

gridsearch:
  batch_size: { lower: 32, upper: 256, type: int }
  lr: { lower: 0.0002, upper: 0.005, type: float }
  # precision: { list: [16-mixed, 32-true, 64-true], type: choice }
  num_rnn_layers:
    {
      lower: 1,
      upper: 5,
      type: int,
      layer_sizes: { lower: 50, upper: 150, layer_type: rnn, varied: True },
    }
  num_lin_layers:
    {
      lower: 1,
      upper: 3,
      type: int,
      layer_sizes: { lower: 10, upper: 100, layer_type: lin, varied: True },
    }
